### ISSUE TITLE
Selection the Harder difficulty sometimes crashes the game

### ISSUE THREAD

**Issue by heavyutils** [hiimjustin000/FakeRate#16] opened 2024-06-27 16:41 UTC
When doing the fake rate sometimes the second you click on "Harder" face the game crashes

**Comment by hiimjustin000** [comment] 2024-06-27 17:02
On where? DIfficulty selection?

**Comment by hiimjustin000** [comment] 2024-06-27 17:07
Also, send the crashlog

**Comment by heavyutils** [comment] 2024-06-27 17:11
Yes on the difficulty selection. Geode didn't generate a new crashlog and it didn't even say Crashed or anything when i reopened the game. It was some windows error thingy or smth but your mod was referenced in it.

**Comment by hiimjustin000** [comment] 2024-06-27 17:15
I can't reproduce this issue. What level did you try to rate as Harder?

**Comment by heavyutils** [comment] 2024-06-27 18:03
"dorabaebasic7" was what failed. I had previously rated it Hard 5* in gd 2.204.

**Comment by heavyutils** [comment] 2024-06-27 18:28
Ok it crashed again but with a log this time
[2024-06-27_20-28-17.log](https://github.com/user-attachments/files/16019420/2024-06-27_20-28-17.log)

**Comment by heavyutils** [comment] 2024-06-27 18:37
boom, now it deleted all my fake rates... :(

**Comment by hiimjustin000** [comment] 2024-06-27 18:43
I'm sorry to hear that.

I'll get to fixing.

**Comment by hiimjustin000** [comment] 2024-06-27 18:58
This was caused by me not properly checking if the More Difficulties mod was enabled. Bug has existed since v1.2.0, probably.

Fixed in v1.2.3

**Closed by hiimjustin000** 2024-06-27 18:58 UTC
