### ISSUE TITLE
Another problem to More difficulties
(Android64) 2.206

### ISSUE THREAD

**Issue by LumerGD120** [hiimjustin000/FakeRate#12] opened 2024-06-10 10:59 UTC
With More difficulties
![Screenshot_2024-06-10-18-56-46-98_73932565f5d18c5d7f2b58eb6d5de17f.jpg](https://github.com/hiimjustin000/FakeRate/assets/147040389/ca1e0eb3-52d7-4954-9fbb-e3d9bf4a55e2)

No More difficulties
![Screenshot_2024-06-10-18-56-17-61_73932565f5d18c5d7f2b58eb6d5de17f.jpg](https://github.com/hiimjustin000/FakeRate/assets/147040389/6e4d47f7-1fa4-450d-8f77-900ef27b19e2)

**Comment by hiimjustin000** [comment] 2024-06-10 11:35
Give me more details. What did you rate the level to?

**Comment by LumerGD120** [comment] 2024-06-10 13:51
> Give me more details. What did you rate the level to?

9 stars

**Comment by hiimjustin000** [comment] 2024-06-10 14:13
This appears to be caused by More Difficulties. I notified Uproxide about this, and I'm hoping she will come with a solution.

**Comment by hiimjustin000** [comment] 2024-06-11 19:20
Fixed in v1.1.9-beta.2

**Closed by hiimjustin000** 2024-06-11 19:20 UTC
