### ISSUE TITLE
#16 got reintroduced

### ISSUE THREAD

**Issue by heavyutils** [hiimjustin000/FakeRate#25] opened 2024-07-03 04:59 UTC
#16 is back So imma revert to an older version until fix

**Comment by hiimjustin000** [comment] 2024-07-04 10:37
How do you reproduce this? I cannot seem to do this myself.

**Comment by heavyutils** [comment] 2024-07-04 10:55
> How do you reproduce this? I cannot seem to do this myself.

Like the one before. Rate a level rated 4, 7, or 9 to anything else, boom

**Comment by hiimjustin000** [comment] 2024-07-04 12:14
Existed since v1.2.7, fixed in v1.2.8

**Closed by hiimjustin000** 2024-07-04 12:14 UTC
