### ISSUE TITLE
Grandpa, Infinite, Mythical And Legendary Demons Are Suposed To Have A Background

### ISSUE THREAD

**Issue by lance21312** [hiimjustin000/FakeRate#36] opened 2024-08-12 13:01 UTC
here is with fake rate:
![Screenshot 2024-08-12 085544](https://github.com/user-attachments/assets/5b9cff6c-ff7d-4271-865c-85f4d5983f91)
and here is without fake rate
![Screenshot 2024-08-12 085601](https://github.com/user-attachments/assets/d15d6f9d-6d3e-4818-8ae9-957813de0f1c)
![Screenshot 2024-08-12 085611](https://github.com/user-attachments/assets/9b63fc6d-2877-480a-a6fe-af32390739b6)
![Screenshot
![Screenshot 2024-08-12 085659](https://github.com/user-attachments/assets/da448030-713e-48f6-905c-6b0f88aa07e5)
 2024-08-12 085641](https://github.com/user-attachments/assets/681928c8-c540-4d48-9b2f-9a3459f7d9e2)
![Screenshot 2024-08-12 085717](https://github.com/user-attachments/assets/5a06d186-b229-4521-803e-6573854d0a93)
![Screenshot 2024-08-12 085659](https://github.com/user-attachments/assets/b8993126-5759-46b1-bba6-79cfbdee9e5c)

**Comment by hiimjustin000** [comment] 2024-08-12 14:22
That's pretty hard to do. This is planned for 1.4.0, which will be in at the most a week or two.

**Comment by hiimjustin000** [comment] 2024-08-12 17:12
In other words, duplicate of #30

**Closed by hiimjustin000** 2024-08-12 17:12 UTC
