### ISSUE TITLE
Godlike faces bug (i can't confirm that fake rate is the problem)

### ISSUE THREAD

**Issue by LumerGD120** [hiimjustin000/FakeRate#27] opened 2024-07-06 04:00 UTC
The godlike faces don't show when outside the the level, let me show you an example

![Screenshot_2024-07-06-11-54-12-69_73932565f5d18c5d7f2b58eb6d5de17f.jpg](https://github.com/hiimjustin000/FakeRate/assets/147040389/d0bbe023-1c48-4967-b9cc-effab36eec88)

![Screenshot_2024-07-06-11-54-08-59_73932565f5d18c5d7f2b58eb6d5de17f.jpg](https://github.com/hiimjustin000/FakeRate/assets/147040389/b6cc3c26-8144-4e41-b24b-1a9c7c3400b2)

Also i disabled texture loader by geode team because that's the problem to the pink box thingy

**Comment by hiimjustin000** [comment] 2024-07-09 20:27
Caused by GodlikeFaces (Will be fixed AdyaGMD/GodLikeFaces#5 if Adya actually becomes active, because it's becoming quite tiring waiting)

**Closed by hiimjustin000** 2024-07-09 20:27 UTC
